# ------------------------------------------------------------------------------------------------ #
# --- Starship configuration --------------------------------------------------------------------- #
# ------------------------------------------------------------------------------------------------ #

format = """$os$username$hostname$directory$git_branch\n$character"""

[username]
format = ' [$user]($style)'
style_user = 'black dimmed bold'
style_root = 'red bold'
show_always = true

[hostname]
ssh_symbol = ' '
ssh_only = false
trim_at = ''
style = 'black dimmed bold'
format = '[@$hostname]($style)  '

[directory]
truncation_length = 3
truncate_to_repo = true
format = '[$read_only]($read_only_style)[$path]($style) '
style = 'white bold'
read_only = ' '
read_only_style = 'white bold'
truncation_symbol = ' /'
home_symbol = '~'
use_os_path_sep = true

[character]
format = '$symbol '
success_symbol = '[](green)'
error_symbol = '[](green)'
vimcmd_symbol = '[](purple)'
vimcmd_replace_one_symbol = '[](yellow)'
vimcmd_replace_symbol = '[](yellow)'
vimcmd_visual_symbol = '[](yellow)'

[git_branch]
symbol = " "
format = " [$symbol$branch(:$remote_branch)]($style)"
style = "bold blue"

[os]
disabled = false

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Gentoo = " "
Illumos = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = " "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "

